name: Deployment pipeline

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  health-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the service health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://pokedexcicdlinux.azurewebsites.net/health
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
      - name: Health check succeeded
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Health check has failed
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Health check has cancelled
        if: ${{ cancelled() }}
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: warn
          details: Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
